### ISSUE TITLE
Backend cfg guard in geode-core/lib.rs is not robust to feature unification (E0428)

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/geode-fem#76]
## Summary

`cargo clippy --all-targets --no-default-features --features ndarray -- -D warnings` (i.e. the ndarray CPU backend *without* `arpack`) fails to compile with:

```
error[E0428]: the name `DefaultBackend` is defined multiple times
error[E0428]: the name `BACKEND_NAME` is defined multiple times
```

## Root cause

`crates/geode-core/src/lib.rs` selects the backend with mutually-exclusive `#[cfg(feature = "wgpu")]` / `#[cfg(feature = "cuda")]` / `#[cfg(feature = "ndarray")]` blocks that each define `pub type DefaultBackend` and `const BACKEND_NAME`. Under `--all-targets`, Cargo feature unification across the package's dev-dependencies re-activates the default `wgpu` feature even when the build is invoked with `--no-default-features --features ndarray`. With **both** `wgpu` and `ndarray` active, the two cfg blocks both compile, producing duplicate definitions instead of tripping the intended `compile_error!` ("enable exactly one backend feature").

This predates the gauge-test work — the cfg blocks were introduced in #6 and the dev-dependency unification hazard is already noted in `crates/geode-core/Cargo.toml` (the comment block around the `[dev-dependencies]` section). It is **not** introduced by #59/#75 (that PR only adds a test file).

## Why it doesn't bite CI today

The CI workflow (`arpack.yml`) builds with `--features arpack` (which implies the intended backend selection), so it never hits the bare `--no-default-features --features ndarray --all-targets` combination. Local `cargo test --no-default-features --features ndarray` (without `--all-targets`) also avoids it.

## Suggested fix

Make the backend guard robust to feature unification rather than assuming exactly one feature is active, e.g. precedence-based selection:

- `#[cfg(feature = "ndarray")]` → ndarray
- `#[cfg(all(feature = "wgpu", not(feature = "ndarray"), not(feature = "cuda")))]` → wgpu
- `#[cfg(all(feature = "cuda", not(feature = "ndarray"), not(feature = "wgpu")))]` → cuda

or gate the dev-dependency that pulls in `wgpu` so `--no-default-features` is genuinely honored under `--all-targets`.

## Provenance

Discovered while reviewing PR #75 (gauge-symmetry test, Epic #57 Phase 1.B). Out of scope for that PR; tracking here per Judge policy on minor concerns.

**Comment by rjwalters** [comment]
## Curator notes

### Reproduction verified

Ran `cargo clippy --all-targets --no-default-features --features ndarray -- -D warnings` at HEAD (`main`, commit 5564f44). Failure reproduces exactly as described:

```
error[E0428]: the name `DefaultBackend` is defined multiple times
   --> crates/geode-core/src/lib.rs:114:1
error[E0428]: the name `BACKEND_NAME` is defined multiple times
   --> crates/geode-core/src/lib.rs:166:1
error: geode-core: backend features `wgpu`, `cuda`, and `ndarray` are mutually exclusive ...
   --> crates/geode-core/src/lib.rs:89:1
```

The `compile_error!` arm at `lib.rs:84-94` does fire (correctly tripping on `(wgpu, ndarray)`), but the duplicate `pub type DefaultBackend` / `const BACKEND_NAME` definitions at `lib.rs:103, 114, 160, 166` *also* compile and emit E0428 first. So the user sees 3 errors instead of 1 actionable one — and even the intended message is wrong, since the failing build did pass `--no-default-features --features ndarray`.

### Source of the feature unification

Confirmed: not the self-edge in `[dev-dependencies]` (that one correctly uses `default-features = false`, see `geode-core/Cargo.toml:55`). The actual source is the **workspace-level dependency from `geode-cli`**:

- `crates/geode-cli/Cargo.toml:15` — `geode-core = { workspace = true }`
- `Cargo.toml:17` — `geode-core = { path = "crates/geode-core" }` (defaults enabled)

When you run `cargo clippy --all-targets` from the workspace root, Cargo unifies features across all targets in the workspace. `geode-cli` pulls `geode-core` with `default = ["wgpu"]`, and the `--features ndarray` flag adds `ndarray` on top. Both backends end up active simultaneously.

### Suggested fix evaluation

The body's "precedence-based selection" sketch works for the duplicate-symbol problem, but the existing `compile_error!` at lines 84-94 also has to be relaxed. Currently it trips on `(wgpu, ndarray)` and `(cuda, ndarray)` — which under the new policy are *expected* combinations (the headless CPU backend deliberately wins over a unified-in wgpu). After the fix the only truly incompatible pair is `(wgpu, cuda)` (both pull native GPU stacks).

Sketch of the minimal patch in `crates/geode-core/src/lib.rs`:

```rust
// Mutual exclusion: only (wgpu, cuda) is actually incompatible. The
// (*, ndarray) combinations are tolerated because Cargo feature
// unification across workspace dev-targets re-activates the default
// wgpu feature even when --no-default-features --features ndarray is
// passed; the headless CPU backend takes precedence in that case.
#[cfg(all(feature = "wgpu", feature = "cuda"))]
compile_error!("geode-core: backends `wgpu` and `cuda` are mutually exclusive.");

#[cfg(not(any(feature = "wgpu", feature = "cuda", feature = "ndarray")))]
compile_error!("geode-core: enable exactly one backend feature: `wgpu`, `cuda`, or `ndarray`.");

// Precedence: ndarray > cuda > wgpu. ndarray wins so CI / headless
// `--features ndarray` builds compile even when feature unification
// silently re-activates wgpu.
#[cfg(feature = "ndarray")]
pub type DefaultBackend = burn::backend::NdArray<f64, i32>;

#[cfg(all(feature = "cuda", not(feature = "ndarray")))]
pub type DefaultBackend = burn::backend::Cuda;

#[cfg(all(feature = "wgpu", not(feature = "ndarray"), not(feature = "cuda")))]
pub type DefaultBackend = burn::backend::Wgpu;

// Same precedence pattern for BACKEND_NAME.
#[cfg(feature = "ndarray")]
const BACKEND_NAME: &str = "ndarray";

#[cfg(all(feature = "cuda", not(feature = "ndarray")))]
const BACKEND_NAME: &str = "cuda";

#[cfg(all(feature = "wgpu", not(feature = "ndarray"), not(feature = "cuda")))]
const BACKEND_NAME: &str = "wgpu";
```

Verified by inspection that this covers all 7 nontrivial feature-set powerset cases (single backend, each pair, all three):

| wgpu | cuda | ndarray | active type | compile_error? |
|---|---|---|---|---|
| on  | off | off | Wgpu                | no  |
| off | on  | off | Cuda                | no  |
| off | off | on  | NdArray<f64,i32>    | no  |
| on  | on  | off | (error)             | yes (wgpu+cuda) |
| on  | off | on  | NdArray<f64,i32>    | no  |
| off | on  | on  | NdArray<f64,i32>    | no  |
| on  | on  | on  | (error)             | yes (wgpu+cuda) |
| off | off | off | (error)             | yes (none enabled) |

Alternative: gate the workspace edge from `geode-cli` with `default-features = false`. That's surgically smaller but only fixes the workspace-root case — any downstream consumer that adds `geode-core` with defaults plus an explicit `ndarray` opt-in would re-hit the same bug. Precedence is more durable.

### Acceptance criteria

1. **Build hygiene gate (primary):** the exact command from the body must succeed with `-D warnings`:
   ```
   cargo clippy --all-targets --no-default-features --features ndarray -- -D warnings
   ```
   from the workspace root. This is the regression check.

2. **CI path stays green:** the existing CI command must still pass unchanged:
   ```
   cargo clippy --tests -p geode-core --no-default-features --features arpack,ndarray -- -D warnings
   ```
   (already in `.github/workflows/arpack.yml` line 62-63).

3. **Default build stays green:** `cargo clippy --all-targets -- -D warnings` (i.e. default `wgpu` backend) continues to compile and `BACKEND_NAME == "wgpu"`.

4. **Backend identity is correct under precedence:** add a unit test or doc-test that asserts `device_info().backend == "ndarray"` when the `ndarray` feature is on, regardless of whether `wgpu` is also active. The simplest form: extend the existing `tests::device_info_is_populated` test in `lib.rs:225-232` with a `#[cfg(feature = "ndarray")] assert_eq!(info.backend, "ndarray");` arm. This is the test that fails under the current buggy state (E0428) and locks in the precedence policy going forward.

5. **CI guard (optional but recommended):** add a job step to `.github/workflows/arpack.yml` that runs the bare reproducer command. Without this, the bug class can silently regress because the canonical CI invocation always passes `--features arpack`.

### Test plan

- [ ] `cargo clippy --all-targets --no-default-features --features ndarray -- -D warnings` passes from `/Users/rwalters/GitHub/geode-fem`
- [ ] `cargo clippy --all-targets -- -D warnings` (default `wgpu`) still passes
- [ ] `cargo test --no-default-features --features ndarray -p geode-core` passes and `device_info_is_populated` confirms `backend == "ndarray"`
- [ ] `cargo test --no-default-features --features arpack,ndarray -p geode-core --release --test sparse_eigensolver -- --ignored` (the CI acceptance test) still passes
- [ ] (Optional) CI workflow adds the `--all-targets --no-default-features --features ndarray` clippy step

### Out of scope

- Re-architecting backend selection beyond cfg-precedence (e.g. runtime backend dispatch, trait-object device).
- Removing the workspace-level default-features activation from `geode-cli` (a separate cleanup; the cfg-precedence fix above subsumes it).
- Adding `wgpu`/`cuda` integration tests on CI (the CI runner is headless ubuntu — neither adapter exists).

### Relevant files

- `crates/geode-core/src/lib.rs:80-100` — `compile_error!` arms (mutual exclusion guard)
- `crates/geode-core/src/lib.rs:102-114` — `DefaultBackend` type alias cfg blocks
- `crates/geode-core/src/lib.rs:159-166` — `BACKEND_NAME` cfg blocks
- `crates/geode-core/src/lib.rs:208-234` — existing `tests` module to extend
- `crates/geode-core/Cargo.toml:26-45` — feature declarations
- `crates/geode-core/Cargo.toml:47-55` — `[dev-dependencies]` (already correctly uses `default-features = false`)
- `crates/geode-cli/Cargo.toml:15` — workspace dep that contributes wgpu under unification
- `.github/workflows/arpack.yml:62-63` — current clippy invocation (uses `arpack,ndarray`, sidesteps the bug)

### Tier

`tier:goal-supporting` — build hygiene fix that keeps the headless CPU backend usable as a development target. Not directly advancing a milestone deliverable, but blocks the kind of local clippy-clean development loop the rest of the project depends on (and removes a footgun for any new contributor who tries the documented `--features ndarray` path).
