### ISSUE TITLE
Bunsen Phase 1 — dependency-wiring spike + one assembly.rs shape_contract! (gate for Epic #355)

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/geode-fem#358]
**Parent epic:** #355 (adopt the Bunsen standard library — machine-checked shape contracts on the FEM tensor pipeline)

This is **Phase 1** of #355: the dependency-wiring spike and a single proof-of-value contract conversion. It is the **gate** — Phases 2–4 are blocked on the integration facts this spike establishes. The Architect validation of #355 (see epic comment) **corrected several load-bearing assumptions** in the epic body; the acceptance criteria below reflect the corrected facts, not the original epic text.

## Architect validation (what changed vs. the epic body)

Confirmed against the registry index and the live tree:

- **`burn 0.21.0` is pinned** — `Cargo.toml:17` (`burn = { version = "0.21", default-features = false, features = ["std"] }`) and `Cargo.lock` (`burn 0.21.0`). HOLDS.
- **`bunsen 0.21.0` exists and requires `burn ^0.21.0`** with `default_features = true` on its burn edge — semver-compatible with our pin. The epic's central "no burn bump" assumption HOLDS. (Latest bunsen is 0.24.2, also on `burn ^0.21.0`.)
- **The `~139 ad-hoc shape-assert sites` figure is high.** Actual measured count in the 6 Tensor-using files (`assembly.rs`, `nedelec_assembly.rs`, `nedelec.rs`, `p1.rs`, `eigen.rs`, `lib.rs`): **31 `.dims()` calls + 64 `assert*` lines = 95 candidate sites** (0 `.shape()` calls). The 6-file set itself is correct. Use ~95, not ~139.
- **CORRECTION — there is NO `contracts` feature and NO `burner` feature on `bunsen 0.21.x`.** The epic's proposed `features = ["contracts", "burner"]` **will not resolve.** The contracts DSL is delivered via the *always-on, non-optional* `bunsen-contracts-macros` dependency, gated only by the `std` feature. So the correct wiring is `default-features = false, features = ["std"]`.
- **CORRECTION — bunsen's DEFAULT features are `["reflection", "train", "testing"]`** (plus `store` from 0.21.3). `train` pulls `burn/train` (the training-loop infra the epic explicitly rules OUT of scope); `reflection` drags in `xot` + `xee-xpath` (a full XPath engine) + `paste` + `spanned_error_message`. **We must build bunsen with `default-features = false`** or we pull all of that in.
- **CORRECTION — the epic says we build burn "with default-features=false, CPU backends".** Half-right: `Cargo.toml` sets `default-features = false, features = ["std"]` at the workspace level, **but `geode-core`'s own `default = ["wgpu"]`** — the default backend is wgpu, and CI uses `--no-default-features --features arpack,ndarray` (`.github/workflows/arpack.yml`). The spike must verify clean builds on **both** the default (wgpu) and the CI (`--no-default-features ... ndarray`/`arpack`) feature combos.
- **Prefer `bunsen 0.21.x` over `0.24.x`.** `0.24.2` adds a *mandatory* `downloader` dep (network/file fetch) even with `default-features = false`; `0.21.x` does not. Pin into the `0.21` line.

## Scope

1. Add `bunsen = { version = "0.21", default-features = false, features = ["std"] }` to `[workspace.dependencies]` (alongside the existing burn line) and wire it into `crates/geode-core/Cargo.toml`.
2. Resolve the lock and **prove no transitive bump / no backend drag**: bunsen must NOT pull `wgpu`/`cuda`/`metal`/`burn-store`/`downloader`/`xot`/`xee-xpath`/`burn/train` into the `geode-core` graph, and must NOT force a `burn` version change. `cargo tree` / `cargo update --dry-run` diffs are the evidence.
3. Convert **ONE** representative shape-assert cluster in `assembly.rs` (it has 4 `.dims()` sites and the cleanest tensor surface) to the `shape_contract!` / `unpack_shape_contract!` DSL as a proof of value. Document the FEM math notation the contract encodes.
4. Confirm the contracts macros are usable under our `std`-only, `#![deny(unsafe_code)]` build (`lib.rs`).

## Acceptance criteria

- [ ] `bunsen = "0.21"` wired with `default-features = false, features = ["std"]`; `Cargo.lock` shows bunsen + `bunsen-contracts-macros` resolved and **burn still at `0.21.0`** (no transitive bump).
- [ ] `cargo tree -p geode-core` shows **no** new `wgpu`/`cuda`/`metal`/`burn-store`/`downloader`/`xot`/`xee-xpath`/`hashbrown`/`burn-train` edges introduced by bunsen (paste the relevant diff in the PR). This is the one real integration risk and the gate's pass/fail signal.
- [ ] Default build (`cargo build -p geode-core`, wgpu) is clean.
- [ ] CI feature combos build + clippy clean: `cargo build -p geode-core --no-default-features --features arpack,ndarray` and `cargo clippy --tests -p geode-core --no-default-features --features arpack,ndarray -- -D warnings`.
- [ ] One `assembly.rs` shape-assert cluster converted to `shape_contract!`, with the encoded FEM shape notation documented; existing tests still pass.
- [ ] `cargo doc -D warnings` (doc-lint gate) and `cargo fmt --check` stay green. (Note: this repo has NO pre-commit fmt hook — run `cargo fmt` explicitly.)
- [ ] PR records the **final resolved bunsen patch version** (within 0.21) and whether `0.21.x` vs `0.24.x` was chosen, with the `downloader`-dep rationale.

## Gate decision for the epic

If criterion #2 (no backend/heavy-dep drag) **fails** and cannot be contained via `default-features = false`, Phases 2–4 should NOT proceed — report back to #355 and the Champion before spinning off Phase 2. If it passes, Phase 2 (contracts across `assembly.rs` + `nedelec_assembly.rs`) becomes unblocked.

---
*Filed by the Loom Architect as the first actionable child of Epic #355, after validating the epic's feasibility claims against the registry index and the live tree.*

**Comment by rjwalters** [comment]
## Builder gate finding: NO-DRAG GATE FAILS — bunsen 0.21.x has no buildable `std`-only configuration

I ran the Phase-1 dependency-wiring spike exactly as specified (workspace + `geode-core` wiring of `bunsen = { version = "0.21", default-features = false, features = ["std"] }`, lock resolution, `cargo tree` evidence). The gate (acceptance criterion #2) **fails**, and per the issue's "Gate decision" section I stopped rather than force it. The failure is a hard, version-line-wide defect in bunsen itself — not something containable via `default-features = false`. Phases 2–4 should **not** proceed on the 0.21.x/0.24.x line as-is.

### What resolved cleanly (the good news)

- `bunsen` resolves to **0.21.3** (latest in the 0.21 line; the highest semver-compatible patch).
- `burn` stays pinned at **0.21.0** — no transitive bump. HOLDS.
- `bunsen` + `bunsen-contracts-macros` both appear in the lock as expected.
- Under the **CI combo** (`--no-default-features --features arpack,ndarray`) bunsen's *compiled* subtree, configured `default-features = false, features = ["std"]`, contains **only** `anyhow`, `bunsen-contracts-macros` (proc-macro), `burn 0.21.0` (the shared instance — `burn-core`/`burn-tensor`/`burn-ndarray`/`burn-nn`/`burn-optim`), `document-features`, `strum`, `serde`, `serde_json`, `thiserror`. **No** `wgpu`/`cuda`/`metal`/`burn-store`/`downloader`/`xot`/`xee-xpath`/`burn-train`. (The `wgpu`/`cuda` you see in the *default* build come from `geode-core`'s own `default = ["wgpu"]` feature flowing through the shared `burn`, via feature unification — not from bunsen.) The lockfile lists `burn-train`/`burn-store`/etc. as package entries, but those are ghosts from bunsen's *unselected* optional features and are never compiled.

So if bunsen built under `std`-only, the no-drag gate would PASS. **It does not build.**

### The blocking defect (reproduced across the entire 0.21.x and 0.24.x lines)

`bunsen`'s `src/lib.rs` declares, **unconditionally**:

```rust
pub mod public {
    pub use burn;
    pub use hashbrown;   // <-- not feature-gated
}
```

but in `bunsen`'s `Cargo.toml`, `hashbrown` is an **optional** dependency whose **only** activating feature is `train`:

```toml
train = ["std", "burn/train", "dep:hashbrown"]
```

There is no other feature that supplies `dep:hashbrown`. Therefore building bunsen with `features = ["std"]` (or any feature set excluding `train`) fails to compile bunsen's own lib:

```
error[E0432]: unresolved import `hashbrown`
  --> bunsen-0.21.3/src/lib.rs:92:13
   |
92 |     pub use hashbrown;
   |             ^^^^^^^^^ no external crate `hashbrown`
```

I verified the `pub use hashbrown;` is present and unconditional, and `hashbrown` is `train`-only, in **0.21.0, 0.21.1, 0.21.2, 0.21.3, and 0.24.2** (downloaded and inspected each `src/lib.rs` + `Cargo.toml`).

### The only feature that fixes the compile (`train`) fails the no-drag gate

Enabling `features = ["train"]` is the sole way to satisfy bunsen's `hashbrown` import. I tested it: under the CI combo it pulls **`burn-train v0.21.0` into geode-core's *compiled* graph** (verified, not a lockfile ghost) plus a new-major `hashbrown v0.17.1` direct edge. `burn-train` is the training-loop infrastructure the epic explicitly rules out of scope and is on the gate's forbidden-edge list. So `train` trades the compile error for a direct gate-criterion-#2 violation.

### Why I can't sidestep via the standalone contracts crate

The `shape_contract!` / `unpack_shape_contract!` `macro_rules!` wrappers live **inside `bunsen` itself** (`src/contracts/macros.rs`) and expand to `$crate::contracts::{ShapeContract, DimExpr, DimMatcher}` — the runtime types are defined in `bunsen`'s own `contracts` module, not in a separately-publishable stable crate. The standalone `bunsen-contracts` runtime crate is **pre-release only** (max `0.21.0-pre.6`, no stable release). So there is no stable, `burn-train`-free crate that delivers the DSL.

### Decision matrix (every option, with the gate outcome)

| bunsen config | compiles? | gate (no-drag) |
|---|---|---|
| `default-features = false, features = ["std"]` (issue's prescription) | ❌ `unresolved import hashbrown` | n/a (won't build) |
| `default-features = false, features = ["train"]` (only hashbrown-supplying feature) | ✅ | ❌ pulls `burn-train` + `hashbrown 0.17` into compiled graph |
| `default` | ✅ | ❌ pulls `burn-train`, `xot`, `xee-xpath`, `burn-store`, … |
| 0.24.x line | same defect ❌ | strictly worse (adds mandatory `downloader`) |

**No configuration of any released bunsen version both compiles and passes the no-drag gate.**

### Recommendation (Champion/epic decision)

Per the issue's gate-decision clause, Phases 2–4 are **blocked** on the integration facts. Options for #355:

1. **Upstream fix** — file a bug on bunsen asking that `pub use hashbrown;` in `mod public` be `#[cfg(feature = "train")]`-gated (or that `hashbrown` move under `std`). Trivial one-line fix; once released on the 0.21 line, this spike re-runs green and the no-drag gate passes (the `std`-only compiled subtree is already proven clean above).
2. **Wait for a stable `bunsen-contracts`** runtime crate (currently pre-release) and depend on `bunsen-contracts` + `bunsen-contracts-macros` directly, bypassing the `bunsen` umbrella entirely.
3. **Vendor** the small `ShapeContract`/`DimExpr`/`DimMatcher` runtime + the `macro_rules!` wrappers (they depend only on `alloc` + the proc-macro), dropping the `bunsen` umbrella dep. Heavier maintenance; loses "adopt the standard library" framing.
4. **Drop adoption** if none of the above is acceptable.

I reverted all spike changes (the `["std"]` wiring can't merge because it doesn't build, and the `assembly.rs` `shape_contract!` conversion can't compile without it). No PR is opened — there is no compiling, gate-passing code change to merge. Marking blocked so the Champion/epic can pick a path.

**Comment by rjwalters** [comment]
Upstream bug filed: **zspacelabs/bunsen#95** — `pub use hashbrown;` at `src/lib.rs:92` is ungated, so any non-`train` build (incl. our required `default-features = false, features = ["std"]`) fails with `E0432: unresolved import hashbrown`. Confirmed by direct source inspection of bunsen 0.21.3 that this re-export is the *sole* blocker — every actual `hashbrown` consumer (`burner::optim`) is already `#[cfg(feature = "train")]`-gated. Suggested one-line fix submitted upstream.

**Decision:** parking this issue `loom:blocked` pending a fixed bunsen 0.21.x release. Once upstream ships the gate, the Phase 1 spike re-runs green (already proven: with a buildable `std`-only config, the no-drag gate passes — no wgpu/cuda/burn-store/downloader/xot/burn-train edges, burn stays 0.21.0). Tracking: https://github.com/zspacelabs/bunsen/issues/95

**Comment by rjwalters** [comment]
**Blocker re-check (2026-07-12 sweep):** upstream zspacelabs/bunsen#95 (ungated `pub use hashbrown`) was **closed 2026-06-24** via "feat: fix hashbrown build with no-train", and bunsen **0.25.0** shipped the same day (`hashbrown` is now an optional dep). However:

- **No fixed 0.21.x exists** — latest 0.21.x is still 0.21.3 (broken). The fix shipped only in 0.25.0.
- **bunsen 0.25.0 carries a mandatory (non-optional, normal-kind) `downloader ^0.2.7` dependency** (plus `directories-next`), per the crates.io index. The no-drag gate this spike already proved for a buildable 0.21.x config explicitly requires **no downloader edge** — so re-running the spike against 0.25.0 would fail the gate as currently specified.
- Good news: bunsen 0.25.0 still tracks `burn ^0.21.0` — the no-burn-bump thesis continues to hold.

**Options for unblocking** (operator/architect call):
1. Ask upstream to gate `downloader` (+ `directories-next`) behind a feature — then 0.25.x becomes viable as-is.
2. Ask upstream for a 0.21.4 backport of the hashbrown gate.
3. Relax the no-drag gate to tolerate `downloader` as a compile-only cost (weigh: it pulls network-download machinery into a deterministic solver's dep tree).

Staying `loom:blocked` pending that call. — sweep bot

**Comment by rjwalters** [comment]
**Upstream PR opened: zspacelabs/bunsen#112** (https://github.com/zspacelabs/bunsen/pull/112) — implements unblock option 1 from the 2026-07-13 re-check: makes `downloader` + `directories-next` optional, activated by the existing `cache` feature (manifest-only, +4/−2; the `src/data/cache/` module and all its consumers were already correctly `cfg`-gated).

Verified locally on upstream main (0.25.0): `--no-default-features --features std` compiles with **no downloader/directories-next edge** in the downstream-visible graph (only via bunsen's self-dev-dep, which doesn't propagate); `cache` and default builds unchanged; clippy clean.

**Once merged + released (any 0.25.x patch), this issue unblocks as-is:** re-run the Phase 1 spike against `bunsen = { version = "0.25", default-features = false, features = ["std"] }` — the hashbrown blocker (#95) is already fixed in 0.25.0, burn stays ^0.21.0 (no bump), and the no-drag gate should now pass. Note 0.25.0 requires edition 2024 / recent MSRV (rust-version 1.94.1 in upstream workspace) — verify our toolchain floor when re-running.

**Comment by rjwalters** [comment]
**Upstream PR zspacelabs/bunsen#112 MERGED** (all CI checks green, same day). `downloader` + `directories-next` are now optional on bunsen main, activated by the `cache` feature.

**Still blocked on the release:** crates.io latest is 0.25.0 (mandatory downloader). Upstream uses release-plz, so the `fix:` commit should cut **0.25.1** automatically on their next release cycle. Once 0.25.1 (or later) appears on crates.io with the optional downloader, this issue unblocks: re-run the Phase 1 spike against `bunsen = { version = "0.25.1", default-features = false, features = ["std"] }` — hashbrown fix (#95) + downloader fix (#112) both in, burn stays ^0.21.0. Verify toolchain floor (upstream workspace pins rust 1.94.1 / edition 2024).

Quick re-check command: `curl -s https://index.crates.io/bu/ns/bunsen | tail -1 | python3 -c "import sys,json; l=json.loads(sys.stdin.read()); print(l['vers'], [(d['name'],d.get('optional')) for d in l['deps'] if d['name']=='downloader'])"`

**Comment by rjwalters** [comment]
**Unblocking via git pin (operator decision):** rather than wait for release-plz to cut 0.25.1, pin bunsen to the #112 merge commit on main:

```toml
bunsen = { git = "https://github.com/zspacelabs/bunsen", rev = "1ff74cd9814d10953e79a995d19db468df4a43ed", default-features = false, features = ["std"] }
```

- Both blockers are in at this rev: #95 hashbrown gate (0.25.0) + #112 optional downloader/directories-next (merged today, all CI green).
- Toolchain floor verified: geode-fem is already edition 2024 / rust-version 1.96.0 ≥ bunsen's 1.94.1; CI runs `dtolnay/rust-toolchain@stable`.
- geode-fem is not published to crates.io, so a git dependency has no downstream cost.
- **Follow-up swap:** when 0.25.1+ ships on crates.io with the optional downloader, replace the git pin with `version = "0.25.1"` (mechanical, one-line).

Note the issue body's `0.21.x` prescription is superseded: the fix line is 0.25 (no 0.21.4 backport exists). The no-drag gate criteria stand unchanged — the spike PR must prove them via `cargo tree` on the pinned rev. Removing `loom:blocked`; proceeding with the Phase 1 spike.
